### ISSUE TITLE
Error importing pyluos.modules (pyluos version 1.4.1)

### ISSUE THREAD

**Issue by agillies8** [pollen-robotics/reachy-2019#66]
Reachy package cannot import pylous.modules. Likely because most recent version of pylous (1.4.1) renamed modules to containers.

To reproduce:

```
from reachy import parts, Reachy

r = Reachy(
    right_arm=parts.RightArm(io='ws', hand='force_gripper'),
    left_arm=parts.LeftArm(io='ws', hand='force_gripper'),
)
```

To fix:

Change line 8 in luos.py to:

`from pyluos.containers import DynamixelMotor
`

**Comment by pierre-rouanet** [comment]
Hi @agillies8,

Thanks for reporting this issue!
It's indeed due to recent API changes in pyluos.
The newest version is actually incompatible with the module version we used. I thus recommend to keep pyluos 1.2.* for the moment.
I've updated the setup.py file accordingly.

We'll update the pyluos version in our next release.
